<<<<<<< Updated upstream
# Generated by Django 4.2.1 on 2023-05-16 11:19
=======
# Generated by Django 4.2.1 on 2023-05-11 11:57
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
